version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/frontend
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop_service.sh
      timeout: 300
      runas: ubuntu

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/start_service.sh
      timeout: 300
      runas: ubuntu
