version: 0.2

phases:
  install:
    commands:
      - echo "Navigating to frontend directory"
      - cd frontend || exit 1
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building project"
      - npm run build

  post_build:
    commands:
      - echo "Zipping build files"
      - cd build
      - zip -r ../frontend.zip .  # ✅ This ensures the zip file is in the correct location
      - cd ..
      - ls -lh  # ✅ Debugging: List files to check if frontend.zip exists

artifacts:
  files:
    - frontend.zip  # ✅ Ensure this matches the created zip file name
  base-directory: .  # ✅ Explicitly tell CodeBuild where to look for frontend.zip
  discard-paths: yes
