version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Building project"
      - npm run build

  post_build:
    commands:
      - echo "Zipping build files"
      - zip -r frontend.zip build/*
      - ls -lh  # Debugging step to verify zip creation

artifacts:
  files:
    - frontend.zip  # ✅ Ensures CodeBuild finds the correct artifact
  discard-paths: yes
